version: '3'
services: 
    redis:
      image: "redis:latest"
    plawnpass:
      build: .
      image: plawnpass
      ports:
        - "5000:4000"
      volumes: 
        - './conf.yaml:/api/conf.yaml'
      depends_on:
        - redis